apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs-sonarr-tv
  namespace: sonarr
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.10.250.254
  share: /mnt/Tank1/media/TV
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-nfs-sonarr-tv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-nfs-sonarr-tv
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 10.10.250.254#/mnt/Tank1/media/TV#sonarr
    volumeAttributes:
      server: 10.10.250.254
      share: /mnt/Tank1/media/TV
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-sonarr-tv
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-sonarr-tv
  storageClassName: sc-nfs-sonarr-tv
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sonarr
  namespace: sonarr
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - sonarr.camelotlab.xyz
      secretName: nginx-wildcard
  rules:
    - host: sonarr.camelotlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      # Add the initContainers section
      initContainers:
      - name: init-permissions
        image: busybox:latest # Use a lightweight image
        command: ['sh', '-c', 'chown -R 1000:1000 /config']
        volumeMounts:
        - name: tv
          mountPath: /tv
        - name: config
          mountPath: /config
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: tv
          mountPath: /tv
        - name: config
          mountPath: /config
      volumes:
      - name: tv
        persistentVolumeClaim:
          claimName: pvc-nfs-sonarr-tv
      - name: config
        persistentVolumeClaim:
          claimName: pvc-lh-sonarr-config