apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      # Add the initContainers section
      initContainers:
      - name: init-permissions
        image: busybox:latest # Use a lightweight image
        command: ['sh', '-c', 'chown -R 1000:1000 /config']
        volumeMounts:
        - name: tv
          mountPath: /tv
        - name: config
          mountPath: /config
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: tv
          mountPath: /tv
        - name: config
          mountPath: /config
      volumes:
      - name: tv
        persistentVolumeClaim:
          claimName: pvc-nfs-sonarr-tv
      - name: config
        persistentVolumeClaim:
          claimName: pvc-lh-sonarr-config