apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-sonarr-config
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-sonarr-config
  storageClassName: sc-nfs-sonarr-config