apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
spec:
  selector:
    app: sonarr # needs to match the metadata.labels.app or template.metadata.app name in deployment/pod yaml
  type: NodePort
  ports:
    - port: 8989 # the local port the app is listening on
      nodePort: 30080 # must be unique across the entire node pool