apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-lidarr-music
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-lidarr-music
  storageClassName: sc-nfs-lidarr-music