apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lidarr-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-config-lidarr
  storageClassName: sc-nfs-truenas1-config