apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs-lidarr-music
  namespace: lidarr
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.10.250.254
  share: /mnt/Tank1/media/Music
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1