apiVersion: v1
kind: Service
metadata:
  name: lidarr
spec:
  selector:
    app: lidarr # needs to match the metadata.labels.app or template.metadata.app name in deployment/pod yaml
  type: NodePort
  ports:
    - port: 8686 # the local port the app is listening on
      nodePort: 30081 # must be unique across the entire node pool