apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      # Add the initContainers section
      initContainers:
      - name: init-permissions
        image: busybox:latest # Use a lightweight image
        command: ['sh', '-c', 'chown -R 1000:1000 /config']
        volumeMounts:
        - name: movies
          mountPath: /movies
        - name: config
          mountPath: /config
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: movies
          mountPath: /movies
        - name: config
          mountPath: /config
      volumes:
      - name: movies
        persistentVolumeClaim:
          claimName: pvc-radarr-movies
      - name: config
        persistentVolumeClaim:
          claimName: pvc-radarr-config