apiVersion: v1
kind: Namespace
metadata:
  name: radarr
  labels:
    name: radarr
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs-radarr-movies
  namespace: radarr
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.10.250.254
  share: /mnt/Tank1/media/movies
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-nfs-radarr-movies
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-nfs-radarr-movies
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 10.10.250.254#/mnt/Tank1/media/Movies#radarr
    volumeAttributes:
      server: 10.10.250.254
      share: /mnt/Tank1/media/Movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-radarr-movies
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-radarr-movies
  storageClassName: sc-nfs-radarr-movies
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
spec:
  selector:
    app: radarr # needs to match the metadata.labels.app or template.metadata.app name in deployment/pod yaml
  type: NodePort
  ports:
    - port: 7878 # the local port the app is listening on
      nodePort: 30082 # must be unique across the entire node pool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      # Add the initContainers section
      initContainers:
      - name: init-permissions
        image: busybox:latest # Use a lightweight image
        command: ['sh', '-c', 'chown -R 1000:1000 /config']
        volumeMounts:
        - name: movies
          mountPath: /movies
        - name: config
          mountPath: /config
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: movies
          mountPath: /movies
        - name: config
          mountPath: /config
      volumes:
      - name: movies
        persistentVolumeClaim:
          claimName: pvc-nfs-radarr-movies
      - name: config
        persistentVolumeClaim:
          claimName: pvc-lh-radarr-config