apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-media-radarr
  storageClassName: sc-nfs-truenas1-media