apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-movies
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-radarr-movies
  storageClassName: sc-nfs-radarr-movies