apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nfs-truenas1-config
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.10.250.254
  share: /mnt/Tank1/k8s/config
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1