apiVersion: v1
kind: Service
metadata:
  name: longhorn-webui
  namespace: longhorn-system
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 30083
      nodePort: 30083
  selector:
    app: longhorn-frontend