apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  selector:
    app: prowlarr # needs to match the metadata.labels.app or template.metadata.app name in deployment/pod yaml
  type: NodePort
  ports:
    - port: 9696 # the local port the app is listening on
      nodePort: 30084 # must be unique across the entire node pool