apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr # Name of the deployment
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: lidarr # Must match labels in the template section
  template:
    metadata:
      labels:
        app: lidarr # Labels must match selector above
    spec:
      containers:
      - name: lidarr # Name of the container
        image: lscr.io/linuxserver/lidarr # Image to use
        ports:
        - containerPort: 8686 # Container port for the app
        volumeMounts:
        - name: media # Name of the volume to mount
          mountPath: /media # Mount path inside the container
        - name: config # Name of the volume to mount
          mountPath: /config # Mount path inside the container
      volumes:
      - name: media # Volume name must match with volumeMounts name
        persistentVolumeClaim:
          claimName: pvc-lidarr-media # The PVC name must exist
      - name: config # Volume name must match with volumeMounts name
        persistentVolumeClaim:
          claimName: pvc-lidarr-config # The PVC name must exist